# Generated by Django 4.1.4 on 2022-12-22 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_updating_comment_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="published_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
